### ISSUE TITLE
collecting metadata from the epa publications collection

### ISSUE THREAD

**Issue by kupad** [AnujanM/EPADocument-Scraper#1]
From what I can gather, the current file can grab the pdf urls, but loses the associated metadata.  I've checked one of the pdfs with exiftool, and it doesn't have any metadata. I've been working on a script that can grab text file versions of the pdfs that DOES have associated metadata in them.  (Those text files a bit harder to get to, it seems). Is this something valuable?

I have a repository up, here with the code, sans the proxy server that prevents rate limiting that i've encountered.
https://github.com/kupad/epa_publications_collection

/cc @titaniumbones

**Comment by AnujanM** [comment]
Yes the current one only gets the pdfs of each of the documents. The EPA doesn't seem to add meta-data to the pdfs. I think you can use this in your repo and combine the meta data from the text files to the pdf. I think @titaniumbones wanted originally both the pdf and the metadata. The text files give an easy way to search through the data and having pdfs just give all the diagrams together so having both should be useful.
